'use client';

import { BiLoaderAlt } from 'react-icons/bi';
import { FiFileText } from 'react-icons/fi';

interface PreviewPaneProps {
  isLoadingDoc: boolean;
  previewSrc: string | null;
  compileLogs: string;
}

export function PreviewPane({ isLoadingDoc, previewSrc, compileLogs }: PreviewPaneProps) {
  if (isLoadingDoc) {
    return (
      <div className="h-full flex items-center justify-center text-white/30 text-sm">
        <BiLoaderAlt size={18} className="animate-spin mr-2" />
        Loading document...
      </div>
    );
  }

  if (previewSrc) {
    return (
      <div className="h-full flex justify-center items-start">
        <iframe title="Compiled PDF preview" src={previewSrc} className="w-full h-full min-h-[840px] bg-white shadow-[0_4px_40px_rgba(0,0,0,0.8)] rounded-sm" />
      </div>
    );
  }

  return (
    <div className="h-full flex items-center justify-center">
      <div className="w-full max-w-xl min-h-[480px] bg-[#11100c] border border-white/5 rounded-sm p-6 text-left">
        <div className="flex items-center gap-3 text-white/65 mb-4">
          <div className="w-10 h-10 rounded-sm bg-white/[0.04] border border-white/8 flex items-center justify-center">
            <FiFileText size={18} />
          </div>
          <div>
            <p className="text-sm text-white/80">PDF Preview</p>
            <p className="text-[11px] text-white/30">The PDF generated by LaTeX-on-HTTP will appear here after you compile.</p>
          </div>
        </div>

        {compileLogs ? (
          <pre className="text-[11px] leading-relaxed whitespace-pre-wrap break-words text-red-200/80 bg-black/20 border border-red-500/10 rounded-sm p-4 overflow-auto max-h-[420px]">
            {compileLogs}
          </pre>
        ) : (
          <div className="h-[360px] border border-dashed border-white/10 rounded-sm flex items-center justify-center text-center text-white/20 text-xs px-6">
            Use the `Compile` button to view the live PDF preview for the current document.
          </div>
        )}
      </div>
    </div>
  );
}
